[package]
name = "node-primitives"
version = "0.23.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://robonomics.network"
repository = "https://github.com/DAO-IPCI/IPCI-blockchain"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.6", default-features = false, features = ["derive"] }
sp-core = { version = "2.0.1", default-features = false }
sp-runtime = { version = "2.0.1", default-features = false }
sp-application-crypto = { version = "2.0.1", default-features = false }
frame-system = { version = "2.0.1", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-application-crypto/std",
    "frame-system/std",
]
