[workspace]
default-members = [ "bin/node/cli" ]
members = [
    "bin/node/cli",
    "bin/node/ipci-runtime",
    "bin/node/rpc",
    "bin/node/primitives",
]

exclude = [
    "vendor",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
