[workspace]
default-members = [ "node/cli" ]
members = [
    "node/cli",
    "node/runtime",
    "node/rpc",
    "node/primitives",
    "pallets/datalog",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
