[package]
name = "node-rpc"
version = "0.23.4"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.0.0"
node-primitives = { version = "0.23.4", path = "../primitives" }
node-runtime = { version = "0.23.4", path = "../runtime" }
pallet-transaction-payment-rpc = { version = "3.0.0" }
sc-client-api = { version = "3.0.0" }
sc-consensus-babe = { version = "0.9.0" }
sc-consensus-babe-rpc = { version = "0.9.0" }
sc-consensus-epochs = { version = "0.9.0" }
sc-finality-grandpa = { version = "0.9.0" }
sc-finality-grandpa-rpc = { version = "0.9.0" }
sc-sync-state-rpc = { version = "0.9.0" }
sc-chain-spec = { version = "3.0.0" }
sc-keystore = { version = "3.0.0" }
sc-rpc-api = { version = "0.9.0" }
sc-rpc = { version = "3.0.0" }
sp-api = { version = "3.0.0" }
sp-block-builder = { version = "3.0.0" }
sp-blockchain = { version = "3.0.0" }
sp-consensus = { version = "0.9.0" }
sp-consensus-babe = { version = "0.9.0" }
sp-runtime = { version = "3.0.0" }
sp-transaction-pool = { version = "3.0.0" }
sp-keystore = { version = "0.9.0" }
substrate-frame-rpc-system = { version = "3.0.0" }
