[package]
name = "node-cli"
version = "0.23.0"
authors = ["Airalab <research@aira.life>"]
description = "IPCI node implementation in Rust & Substrate."
build = "build.rs"
edition = "2018"
license = "Apache-2.0"
homepage = "https://robonomics.network"
repository = "https://github.com/DAO-IPCI/IPCI-blockchain"
default-run = "ipci"

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "DAO-IPCI/IPCI-blockchain" }
is-it-maintained-open-issues = { repository = "DAO-IPCI/IPCI-blockchain" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "ipci"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
futures = { version = "0.3.9", features = ["compat"] }
serde = { version = "1.0.106", features = ["derive"]}
codec = { package = "parity-scale-codec", version = "1.3.6" }
structopt = { version = "0.3.8", optional = true }
hex-literal = "0.3.1"
log = "0.4"

# primitives
node-primitives = { path = "../primitives", default-features = false }
sp-authority-discovery = { version = "2.0.1" }
sp-consensus = { version = "0.8.1" }
sp-consensus-babe = { version = "0.8.1" }
sp-finality-grandpa = { version = "2.0.1" }
sp-api = { version = "2.0.1" }
sp-core = { version = "2.0.1" }
sp-session = { version = "2.0.1" }
sp-runtime = { version = "2.0.1" }
sp-offchain = { version = "2.0.1" }
sp-inherents = { version = "2.0.1" }
sp-timestamp = { version = "2.0.1" }
sp-trie = { version = "2.0.1" }
sp-blockchain = { version = "2.0.1" }
sp-block-builder = { version = "2.0.1" }
sp-transaction-pool = { version = "2.0.1" }

# client dependencies
sc-basic-authorship = { version = "0.8.1" }
sc-chain-spec = { version = "2.0.1" }
sc-client-db = { version = "0.8.1" }
sc-client-api = { version = "2.0.1" }
sc-consensus = { version = "0.8.1" }
sc-consensus-babe = { version = "0.8.1" }
sc-consensus-slots = { version = "0.8.1" }
sc-finality-grandpa = { version = "0.8.1" }
sc-informant = { version = "0.8.1" }
sc-keystore = { version = "2.0.1" }
sc-network = { version = "0.8.1" }
sc-offchain = { version = "2.0.1" }
sc-service = { version = "0.8.1", default-features = false }
sc-tracing = { version = "2.0.1" }
sc-transaction-pool = { version = "2.0.1" }
sc-telemetry = { version = "2.0.1" }
frame-benchmarking = { version = "2.0.1" }

# frame dependencies
frame-system-rpc-runtime-api = { version = "2.0.1" }
sc-executor = { version = "0.8.1" }
sc-rpc = { version = "2.0.1" }
sc-authority-discovery = { version = "0.8.1" }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.1" }
pallet-im-online  = { version = "2.0.1" }
pallet-indices  = { version = "2.0.1" }
pallet-authority-discovery  = { version = "2.0.1" }
pallet-staking  = { version = "2.0.1" }

# node-specific dependencies
node-rpc = { path = "../rpc" }
ipci-runtime = { path = "../ipci-runtime" }


# CLI-specific dependencies
sc-cli = { version = "0.8.1", optional = true }
frame-benchmarking-cli = { version = "2.0.1", optional = true }

[build-dependencies]
ipci-runtime = { path = "../ipci-runtime" }
sc-cli = { version = "0.8.1", optional = true }
frame-benchmarking-cli = { version = "2.0.1", optional = true }
substrate-build-script-utils = { version = "2.0.1" }
vergen = { version = "3.1.0", optional = true }
structopt = { version = "0.3.8", optional = true }

[features]
default = [
    "cli",
    "wasmtime",
]

## Enable Wasmtime virtual machine.
wasmtime = [
    "sc-service/wasmtime",
    "sc-cli/wasmtime",
]

## Enable Console Line Interface basic features.
cli = [
    "sc-cli",
    "vergen",
    "structopt",
    "sc-service/db",
    "frame-benchmarking-cli",
]

## Enable runtime benchmarking support.
runtime-benchmarks = [
    "ipci-runtime/runtime-benchmarks",
    "frame-benchmarking-cli",
]
