[package]
name = "node-cli"
version = "0.23.0"
authors = ["Airalab <research@aira.life>"]
description = "IPCI node implementation in Rust & Substrate."
build = "build.rs"
edition = "2018"
license = "Apache-2.0"
homepage = "https://robonomics.network"
repository = "https://github.com/airalab/robonomics" 
default-run = "ipci"

#[badges]
#maintenance = { status = "actively-developed" }
#is-it-maintained-issue-resolution = { repository = "airalab/robonomics" }
#is-it-maintained-open-issues = { repository = "airalab/robonomics" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "ipci"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
serde = { version = "1.0.106", features = ["derive"]}
codec = { package = "parity-scale-codec", version = "1.3.5" }
structopt = { version = "0.3.8", optional = true }
hex-literal = "0.3.1"
log = "0.4"

# primitives
node-primitives = { path = "../primitives", default-features = false }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# client dependencies
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-informant = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-finality-grandpa-warp-sync = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# frame dependencies
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-im-online  = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-indices  = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-authority-discovery  = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-staking  = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }


# cumulus dependencies
#cumulus-primitives = { version = "0.1.0", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1",  optional = true }
#cumulus-consensus = { version = "0.1.0", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1",  optional = true }
#cumulus-collator = { version = "0.1.0", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1",  optional = true }
#cumulus-network = { version = "0.1.0", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1",  optional = true }
#cumulus-service = { version = "0.1.0", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1",  optional = true }

# polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }

# node-specific dependencies
node-rpc = { path = "../rpc" }
ipci-runtime = { path = "../ipci-runtime" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# CLI-specific dependencies
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }

# Browser bundle build support
wasm-bindgen = { version = "0.2.69", optional = true }
wasm-bindgen-futures = { version = "0.4.19", optional = true }
substrate-browser-utils = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }

# Robonomics-specific dependencies
rosrust = { version = "0.9.5", optional = true }

[build-dependencies]
ipci-runtime = { path = "../ipci-runtime" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
vergen = { version = "3.1.0", optional = true }
structopt = { version = "0.3.8", optional = true }

[features]
default = [
    "cli",
    "wasmtime",
]

## Enable Wasmtime virtual machine.
wasmtime = [
    "sc-service/wasmtime",
    "sc-cli/wasmtime",
]

## Enable Console Line Interface basic features.
cli = [
    "sc-cli",
    "vergen",
    "structopt",
    "sc-service/db",
    "frame-benchmarking-cli",
]

## Enable browser bundle features.
browser = [
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "substrate-browser-utils",
]

## Enable runtime benchmarking support.
runtime-benchmarks = [
    "ipci-runtime/runtime-benchmarks",
    "frame-benchmarking-cli",
    "frame-benchmarking",
]
